### PR TITLE
Completed US-11: Homepage #18

### PR DESCRIPTION
**Pull request by adamelshafei**
Added the feature set to the homepage (#18). Also added a basic footer (will be styled further).

### CODE REVIEW

**Review by charbelchahine — COMMENTED** [review]
The features section looks on point, exactly how I picture both our work coming together.
Also I shouldn't be able to scroll left or right on the website, make sure to fix that.
Other than that once the footer is fixed at the bottom the homepage will look great. Good work!

**Review by afiorito — APPROVED** [review]
Homepage looks good. Your css is almost perfect, just make more use of nesting and try to avoid ids. Good job. I will fix the little glitches

**Review by vartanbeno — COMMENTED** [review]
Homepage looks niceee

**Review by FozAhm — COMMENTED** [review]
Looks good, nice homepage!

**Review by FrankSauve — COMMENTED** [review]
Looks really good! Great work

**Pull request merged**
