### PR TITLE
Completed US-07: User Profile #8

### PR DESCRIPTION
**Pull request by dstroppolo**
Added the profile page and its router. (#8)
Created the button components.
Added a DocumentArea component to the profile page, this might be removed at a later time.
Still needs the sidebar and navbar components.

### CODE REVIEW

**Review by FozAhm — COMMENTED** [review]
Nice work!

**Review by vartanbeno — COMMENTED** [review]
Niceee

**Review by afiorito — APPROVED** [review]
You got the main components for the profile page, great job.

**Review by FrankSauve — COMMENTED** [review]
Looks great!

**Comment by momo2793** [comment]
good stuff

**Review by momo2793 — COMMENTED** [review]
Looks really good!

**Comment by adamelshafei** [comment]
Looks good!

**Pull request merged**
