### PR TITLE
Added GET request for Courses and Documents

### PR DESCRIPTION
**Pull request by FrankSauve**
Completed a task for US-08: Adding Courses #9

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
Your solution works, but you used headers instead of params and it will make it harder for the frontend guys

**Review by momo2793 — COMMENTED** [review]
Good stuff

**Review by FozAhm — COMMENTED** [review]
Good to have add course back end functionality

**Comment by dstroppolo** [comment]
Easy to work with on the front end side nice work

**Pull request merged**
