### PR TITLE
Added name and type fields in signup page

### PR DESCRIPTION
**Pull request by vartanbeno**
Completed task for (#46). I added a name field as well as a type field; the user will be able select among Student, Teacher or Teaching Assistant.

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
Awesome work on this. Looks great. I will add the backend logic for this. Thanks.

**Review by dstroppolo — COMMENTED** [review]
looks good on the website and it fits well with the theme.

**Review by FozAhm — COMMENTED** [review]
Good Work on getting user roles now, great feature!

**Comment by FrankSauve** [comment]
Great feature to have, good work

**Pull request merged**
