### PR TITLE
Completed US-10: Navbar #17

### PR DESCRIPTION
**Pull request by vartanbeno**
Added a navbar (#17) to provide navigation for the site

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
Loving this navbar, really brings the site together. Good job.

**Review by FozAhm — COMMENTED** [review]
Header and Navbar GUI look great!

**Comment by momo2793** [comment]
navbar looks great!

**Review by momo2793 — COMMENTED** [review]
navbar looks great!

**Pull request merged**
