### PR TITLE
Added courses database and post request

### PR DESCRIPTION
**Pull request by FrankSauve**

### CODE REVIEW

**Review by afiorito — CHANGES_REQUESTED** [review]
Once you get your course object from the db (.then course), you don't need to create a jwt token. The jwt token is only for users. Just send back a json response with the course object.

**Review by afiorito — COMMENTED** [review]
The change looks good now, good job

**Comment by momo2793** [comment]
good stuff

**Comment by FozAhm** [comment]
Good backend work!

**Review by FozAhm — COMMENTED** [review]
Good backend work!

**Review by vartanbeno — COMMENTED** [review]
Great work!

**Pull request merged**
