### PR TITLE
Refactored document area to follow best practices

### PR DESCRIPTION
**Pull request by afiorito**
- added props to super call
- added placeholder state to state object
- made number of columns responsive based on screen size
- moved document area to dashboard

### CODE REVIEW

**Comment by dstroppolo** [comment]
refactor looks great, styling is spot on

**Comment by FozAhm** [comment]
Like the fact that the screen automatically scales!

**Comment by FrankSauve** [comment]
Good job looks great

**Review by FozAhm — COMMENTED** [review]
Like the fact that the screen automatically scales!

**Pull request merged**
