### PR TITLE
Unit test for US-05

### PR DESCRIPTION
**Pull request by adamelshafei**
**US-05**: [__tests__/censoring-comments.test.js](https://github.com/a-fiorito/NoteShare/blob/master/__tests__/censoring-comments.test.js)

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
The sample comments are a bit aggressive, but it works good job

**Review by vartanbeno — COMMENTED** [review]
Lovely

**Review by FozAhm — COMMENTED** [review]
Nice test on filtering!

**Comment by FrankSauve** [comment]
Nice work!

**Pull request merged**
