### PR TITLE
Completed US-13: Displaying Documents #20

### PR DESCRIPTION
**Pull request by dstroppolo**
The document area (#20), which should appear next to the sidebar and under the nav bar on the dashboard has been added. It uses a placeholder image which will probably be replaced eventually.

### CODE REVIEW

**Comment by a-fiorito** [comment]
good job

**Comment by FozAhm** [comment]
GUI placeholder and PDF loader looks good!!

**Review by afiorito — COMMENTED** [review]
good job, just keep in mind that when calling super() in a component, you will want to pass props: super(props);

**Review by vartanbeno — COMMENTED** [review]
Looks good!

**Comment by adamelshafei** [comment]
Good job with the responsive resizing!

**Review by momo2793 — COMMENTED** [review]
Nice work

**Pull request merged**
