### PR TITLE
Unit Tests For US-02

### PR DESCRIPTION
**Pull request by dstroppolo**
Tests:
- if the upload modal button will call the upload function
- if files dropped on the upload modal are properly added to the state
- if the upload function is successful
- if the uploaded files are added to the dashboard

**Unit Test**: [__tests__/upload-documents.test.js](https://github.com/a-fiorito/NoteShare/blob/master/__tests__/upload-documents.test.js)

### CODE REVIEW

**Comment by afiorito** [comment]
Great job!

**Review by FozAhm — COMMENTED** [review]
Awesome work

**Comment by FrankSauve** [comment]
Great work!

**Review by vartanbeno — COMMENTED** [review]
Good work!

**Pull request merged**
