### PR TITLE
Added upload modal and connect view to backend

### PR DESCRIPTION
**Pull request by dstroppolo**
Readded my part:
Added upload button to dashboard
Now able to upload documents.

Comletes the tasks for 
US-02: Uploading Documents (#3)

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
Great work on this! The uploading functionality works well.

**Review by vartanbeno — COMMENTED** [review]
Nice work man

**Comment by FrankSauve** [comment]
Looks amazing great work!

**Review by momo2793 — COMMENTED** [review]
Looks great!

**Review by FozAhm — COMMENTED** [review]
Good Upload work

**Pull request merged**
