### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by FozAhm**
Updated and Reorganized Slack Conversations, Meeting Minutes, Reference Documents, Reference Pictures and Meeting Audio.

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
Good job keeping everything organized, looks great

**Review by FrankSauve — COMMENTED** [review]
Very well organized good work!

**Comment by dstroppolo** [comment]
thanks for keeping up to date, good work

**Review by vartanbeno — COMMENTED** [review]
Nice work

**Comment by charbelchahine** [comment]
organized and helpful!

**Pull request merged**
