### PR TITLE
Added the Comments in the database

### PR DESCRIPTION
**Pull request by FrankSauve**
Completed task for (#5). There is now a Comments table that is linked to users and documents.
To post a new comment : axios('/comments')
with body: {commentBody, userId, documentId}.
To load comments for a document: axios('/comments/documentId-here')

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
Awesome work on this, works well.

**Comment by dstroppolo** [comment]
thanks for doing this so quickly, i can get started on my part now

**Review by vartanbeno — COMMENTED** [review]
Good work!

**Review by FozAhm — COMMENTED** [review]
Good to have comments now 👍

**Review by momo2793 — COMMENTED** [review]
Clean!

**Pull request merged**
