### PR TITLE
Unit tests for US-04, US-15

### PR DESCRIPTION
**Pull request by charbelchahine**
**US-04**: [__tests__/add-comment.test.js](https://github.com/a-fiorito/NoteShare/blob/master/__tests__/add-comment.test.js)
**US-15**: [__tests__/profile-stats.test.js](https://github.com/a-fiorito/NoteShare/blob/master/__tests__/profile-stats.test.js)

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
looks good thanks

**Review by vartanbeno — COMMENTED** [review]
good job

**Review by FozAhm — COMMENTED** [review]
Good job on the unit tests

**Comment by FrankSauve** [comment]
Well done!

**Pull request merged**
