### PR TITLE
Completed US-05: Censoring Comments (#6)

### PR DESCRIPTION
**Pull request by adamelshafei**
Completed tasks for (#6). Comment filtering JSX function made

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
Clean comments coming to Noteshare in the near future. Nice work

**Comment by FrankSauve** [comment]
Good job implementing this

**Review by vartanbeno — COMMENTED** [review]
Nice work!

**Review by FozAhm — COMMENTED** [review]
Nice to have censoring capability

**Pull request merged**
