### PR TITLE
Completed US-14: Comment Area #33

### PR DESCRIPTION
**Pull request by adamelshafei**
Added the comments (#33) with a popup feature( Front end feature only so far ). This uses the skylight component http://marcio.github.io/react-skylight/ that can be installed by npm install react-skylight

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
Good work on the comment area looks like you're learning react well.

**Comment by FrankSauve** [comment]
Comment popups look really good, well done!

**Review by vartanbeno — COMMENTED** [review]
Great work!

**Review by FozAhm — COMMENTED** [review]
Nice comment section

**Pull request merged**
