### PR TITLE
Completed Downloadable PDFs

### PR DESCRIPTION
**Pull request by charbelchahine**
You can now click on the download icon under the PDF you wish to download. (#4)
Also added a scroll feature for the homepage, click on "Learn More" to see it in action.

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
It works great!! Awesome work on this.

**Comment by FrankSauve** [comment]
Works really great! Good job

**Review by momo2793 — COMMENTED** [review]
The scrolling feature looks great

**Review by FozAhm — COMMENTED** [review]
Looks good!

**Review by vartanbeno — COMMENTED** [review]
Flawless

**Pull request merged**
