### PR TITLE
Homepage (first half)

### PR DESCRIPTION
**Pull request by charbelchahine**
Coded the first half of the homepage (#18) mockup Adam and I agreed on. Consists of a welcome header, with the buttons 'Get Started' which redirects to the Sign-Up page, and 'Learn More' which the page scrolls down to the list of features NoteShare provides (second half of the homepage coded by Adam).

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
The homepage looks awesome, going to be great for users who are visiting the site for the first time. Nice choice of fonts.

**Review by dstroppolo — COMMENTED** [review]
looks like its off to a good start

**Review by FozAhm — COMMENTED** [review]
Great Looking Homepage!

**Review by vartanbeno — COMMENTED** [review]
Homepage is beautiful, keep it up

**Review by FrankSauve — COMMENTED** [review]
The homepage looks really nice great work!

**Comment by momo2793** [comment]
the homepage looks really good

**Comment by Adam-shafey** [comment]
Looks great! good job!

**Review by momo2793 — COMMENTED** [review]
real good stuff

**Review by adamelshafei — COMMENTED** [review]
Looks great! good job!

**Pull request merged**
