### PR TITLE
Completed US-04: Leaving Comments on Documents #5

### PR DESCRIPTION
**Pull request by dstroppolo**
Completed the task for (#5). A user can now view comments left on documents and leave their own comments.

### CODE REVIEW

**Review by afiorito — APPROVED** [review]
This is great. I fixed a few things (see commit). This is a really neat feature to have for our app. Good work.

**Review by vartanbeno — COMMENTED** [review]
Great work on an important feature

**Review by FozAhm — COMMENTED** [review]
Great work on comment system.

**Review by momo2793 — COMMENTED** [review]
Really Good stuff

**Comment by FrankSauve** [comment]
Looks really great, well done

**Pull request merged**
