### PR TITLE
Completed US-01: Website Login #2

### PR DESCRIPTION
**Pull request by afiorito**
Allows user to login and signup. (#2)
please look at the code and try to understand it

### CODE REVIEW

**Comment by FozAhm** [comment]
The UI looks great, works without a glitch in terms of authentications and switches between sign in/sign up well

**Review by FozAhm — COMMENTED** [review]
The UI looks great, works without a glitch in terms of authentications and switches between sign in/sign up well

**Review by dstroppolo — COMMENTED** [review]
really impressive, great work

**Comment by adamelshafei** [comment]
great UI, we'll need to apply the theme once we decide on one!

**Comment by momo2793** [comment]
great stuff!!

**Pull request merged**
